### ISSUE TITLE
Exporting does not work on 0.8.3

### ISSUE THREAD

**Issue by efox29** [jetperch/pyjoulescope_ui#47]
When trying to export on 0.8.3 it does not save the data. 

I have tried uninstalling and reinstalling, restarting machine .

I reverted back to 0.7.0 and was able to export data.

**Comment by mliberty1** [comment]
Behavior confirmed on Win10x64.
Select View → Oscilloscope.
Add dual markers to data.
Right click on Dual Marker → Export to JLS
Exits without displaying any error, but log says:

```
ERROR:2020-02-24 11:46:23,042:range_tool.py:45:joulescope_ui.range_tool:During range tool run()
Traceback (most recent call last):
  File "joulescope_ui\range_tool.py", line 43, in run
  File "joulescope_ui\exporter.py", line 48, in run
  File "joulescope_ui\exporter.py", line 87, in _export_jls
TypeError: __init__() got an unexpected keyword argument 'sampling_frequency'
```

Simple fix.  Will get a 0.8.4 release out this week.
